#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Elegant Evening Dresses|Charming Gowns 2016|Demure Celebrity Dresses

# Short bio or description (displayed in the header)
description: Customers can browse the vast online selection and choose their favorite dresses with great satisfaction. Hope you have a comfortable travel of shopping.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /static/img/avatar.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram: 
  linkedin:
  pinterest:
  rss: true # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: #jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

related-sites:
  - holein.github.io 
  - variousweddingdress.github.io 
  - colorfulpromdress.github.io 
  - bonnyweddingdress.github.io 
  - charmingbridaldress.github.io 
  - weddingstyledress.github.io 
  - sexyeveningdress.github.io 
  - uniqueproms.github.io 
  - compellingdress.github.io 
  - exquisiteweddings.github.io 
  - glamorouspartydress.github.io 
  - prettycelebritydress.github.io 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://colorfulpromdress.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
paginate: 10
paginate_path: "page:num"

collections:
  my_tags:
    output: true
    permalink: /tag/:name/
  my_categories:
    output: true
    permalink: /category/:name/
  my_date:
    output: true
    permalink: /archives/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag
  -
    scope:
      path: ""
      type: my_date
    values:
      layout: archive